/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj.admin;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import oodj.assignment.*;
import oodj.login.loginselection;

/**
 *
 * @author User
 */
public class adminMenu extends userAttribute {
    User adm = new User();
    /**
     * Creates new form adminMenu
     */
    public adminMenu() {
        initComponents();
        jLabel1.setText("Welcome back, " + adm.userName + "!");
        assignVar();
        setLocationRelativeTo(null);    
        setVisible(true);
    }
    
    public adminMenu(String id, String name, String mail, String pw) {
        initComponents();
        jLabel1.setText("welcome back, " + adm.userName + "!");
        assignVar();
        setLocationRelativeTo(null);    
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lectRegisterBtn = new javax.swing.JButton();
        lectPass = new javax.swing.JTextPane();
        lectMail = new javax.swing.JTextPane();
        lectName = new javax.swing.JTextPane();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        studName = new javax.swing.JTextPane();
        studMail = new javax.swing.JTextPane();
        studPass = new javax.swing.JTextPane();
        studIntakeBox = new javax.swing.JComboBox<>();
        studRegisterBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        assignLBox = new javax.swing.JComboBox<>();
        assignButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        adName = new javax.swing.JTextPane();
        adMail = new javax.swing.JTextPane();
        adPass = new javax.swing.JTextPane();
        adRegisterBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        editStudMail = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        editStudName = new javax.swing.JTextPane();
        editStudentBtn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        editSIntBox = new javax.swing.JComboBox<>();
        editStudentBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        editStudPass = new javax.swing.JTextPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        editLectName = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        editLectMail = new javax.swing.JTextPane();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        editLectPass = new javax.swing.JTextPane();
        editLectBox = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        editLecturerBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        editProjName = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        editProjMail = new javax.swing.JTextPane();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        editProjPass = new javax.swing.JTextPane();
        editProjBox = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        editProjectBtn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        editAdBox = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        editAdName = new javax.swing.JTextPane();
        editAdminBtn = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        editAdMail = new javax.swing.JTextPane();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        editAdPass = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Welcome, ");

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Enter Lecturer Password :");

        jLabel10.setText("Enter Lecturer Email :");

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Note : Lecturer ID will automatically be assigned");

        jLabel12.setText("Enter Lecturer Name :");

        lectRegisterBtn.setText("Register");
        lectRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectRegisterBtnActionPerformed(evt);
            }
        });

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Project Manager?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox2)
                            .addComponent(lectMail, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(lectName, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(lectPass, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(lectRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lectMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lectPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jCheckBox2))
                .addGap(50, 50, 50)
                .addComponent(lectRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Register Lecturers", jPanel1);

        jLabel2.setText("Enter Student Name :");

        jLabel3.setText("Enter Student Email :");

        jLabel4.setText("Enter Student Password :");

        jLabel5.setText("Select Intake :");

        jLabel6.setText("without intake? ");

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        studRegisterBtn.setText("Register");
        studRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studRegisterBtnActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Note : Student ID will automatically be assigned");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox1)
                            .addComponent(studMail, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(studName, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(studPass, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(studIntakeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel7)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(studRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(studName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(studMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(studPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBox1))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(studIntakeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(studRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("Register Students", jPanel2);

        jLabel8.setText("Select lecturer : ");

        assignButton.setText("Assign");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(78, 78, 78)
                .addComponent(assignLBox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(assignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignLBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(75, 75, 75)
                .addComponent(assignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Assign Project Manager", jPanel5);

        adRegisterBtn.setText("Register");
        adRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adRegisterBtnActionPerformed(evt);
            }
        });

        jLabel15.setText("Enter Admin Name :");

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Note : admin ID will automatically be assigned");

        jLabel17.setText("Enter Admin Email :");

        jLabel18.setText("Enter Admin Password :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel15))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adMail, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(adName, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(adPass, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel16))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(adRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(adName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(adMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(adPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(adRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Register Admins", jPanel6);

        jScrollPane2.setViewportView(editStudMail);

        jScrollPane1.setViewportView(editStudName);

        editStudentBtn.setText("Save Changes");
        editStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentBtnActionPerformed(evt);
            }
        });

        jLabel22.setText("Intake :");

        jLabel21.setText("Password :");

        jLabel20.setText("Email :");

        jLabel19.setText("Name :");

        editStudentBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentBoxActionPerformed(evt);
            }
        });

        jLabel14.setText("Select Student :");

        jScrollPane3.setViewportView(editStudPass);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(editStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(editStudentBox, 0, 201, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addComponent(editSIntBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(editStudentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(editSIntBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(editStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jTabbedPane2.addTab("Student", jPanel8);

        jScrollPane6.setViewportView(editLectName);

        jScrollPane5.setViewportView(editLectMail);

        jLabel26.setText("Select Lecturer :");

        jScrollPane4.setViewportView(editLectPass);

        editLectBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLectBoxActionPerformed(evt);
            }
        });

        jLabel25.setText("Name :");

        jLabel24.setText("Email :");

        jLabel23.setText("Password :");

        editLecturerBtn.setText("Save Changes");
        editLecturerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLecturerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6)
                            .addComponent(editLectBox, 0, 201, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane4)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(editLecturerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(editLectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(editLecturerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane2.addTab("Lecturer", jPanel9);

        jScrollPane7.setViewportView(editProjName);

        jScrollPane8.setViewportView(editProjMail);

        jLabel27.setText("Select Project Manager :");

        jScrollPane9.setViewportView(editProjPass);

        editProjBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProjBoxActionPerformed(evt);
            }
        });

        jLabel28.setText("Name :");

        jLabel29.setText("Email :");

        jLabel30.setText("Password :");

        editProjectBtn.setText("Save Changes");
        editProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProjectBtnActionPerformed(evt);
            }
        });

        jLabel31.setText("Back to Lecturer? ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7)
                            .addComponent(editProjBox, 0, 201, Short.MAX_VALUE)
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane9)
                            .addComponent(jCheckBox3)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(editProjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(editProjBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(editProjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane2.addTab("Project Manager", jPanel10);

        editAdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdBoxActionPerformed(evt);
            }
        });

        jLabel32.setText("Name :");

        jLabel33.setText("Email :");

        jLabel34.setText("Password :");

        jScrollPane10.setViewportView(editAdName);

        editAdminBtn.setText("Save Changes");
        editAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdminBtnActionPerformed(evt);
            }
        });

        jScrollPane11.setViewportView(editAdMail);

        jLabel35.setText("Select Admin :");

        jScrollPane12.setViewportView(editAdPass);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane10)
                            .addComponent(editAdBox, 0, 201, Short.MAX_VALUE)
                            .addComponent(jScrollPane11)
                            .addComponent(jScrollPane12)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(editAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(editAdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(editAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane2.addTab("Admin", jPanel3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Edit Details", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(logoutBtn)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logoutBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        loginselection log = new loginselection();
        dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void editAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAdminBtnActionPerformed
        try {
            BufferedReader reader = new BufferedReader(new FileReader(Assignment.user));
            StringBuilder build = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                String[] col = line.split(", ");
                if (col[0].equals(editAdBox.getSelectedItem())) {
                    col[1] = editAdName.getText();
                    col[2] = editAdMail.getText();
                    col[3] = editAdPass.getText();
                }
                build.append(String.join(", ", col)).append("\n");
            }
            reader.close();

            BufferedWriter writer = new BufferedWriter(new FileWriter(Assignment.user));
            writer.write(build.toString());
            writer.close();

            new statusCheck(true, "editted successfully");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editAdminBtnActionPerformed

    private void editAdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAdBoxActionPerformed
        String admID = (String) editAdBox.getSelectedItem();
        try {
            BufferedReader admin = new BufferedReader(new FileReader(Assignment.user));
            String line;

            while ((line = admin.readLine()) != null) {
                String[] adm = line.split(", ");
                if (adm[0].equals((admID))) {
                    editAdName.setText(adm[1]);
                    editAdMail.setText(adm[2]);
                    editAdPass.setText(adm[3]);
                    break;
                }
            }
            admin.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editAdBoxActionPerformed

    private void editProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProjectBtnActionPerformed
        try {
            BufferedReader reader = new BufferedReader(new FileReader(Assignment.user));
            StringBuilder build = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                String[] col = line.split(", ");
                if (col[0].equals(editProjBox.getSelectedItem())) {
                    col[1] = editProjName.getText();
                    col[2] = editProjMail.getText();
                    col[3] = editProjPass.getText();
                    if (jCheckBox3.isSelected()) {
                        col[4] = "l";
                    }
                }
                build.append(String.join(", ", col)).append("\n");
            }
            reader.close();

            BufferedWriter writer = new BufferedWriter(new FileWriter(Assignment.user));
            writer.write(build.toString());
            writer.close();

            new statusCheck(true, "editted successfully");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editProjectBtnActionPerformed

    private void editProjBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProjBoxActionPerformed
        String lectID = (String) editProjBox.getSelectedItem();
        try {
            BufferedReader project = new BufferedReader(new FileReader(Assignment.user));
            String line;

            while ((line = project.readLine()) != null) {
                String[] proj = line.split(", ");
                if (proj[0].equals((lectID))) {
                    editProjName.setText(proj[1]);
                    editProjMail.setText(proj[2]);
                    editProjPass.setText(proj[3]);
                    break;
                }
            }
            project.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editProjBoxActionPerformed

    private void editLecturerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLecturerBtnActionPerformed
        try {
            BufferedReader reader = new BufferedReader(new FileReader(Assignment.user));
            StringBuilder build = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                String[] col = line.split(", ");
                if (col[0].equals(editLectBox.getSelectedItem())) {
                    col[1] = editLectName.getText();
                    col[2] = editLectMail.getText();
                    col[3] = editLectPass.getText();
                }
                build.append(String.join(", ", col)).append("\n");
            }
            reader.close();

            BufferedWriter writer = new BufferedWriter(new FileWriter(Assignment.user));
            writer.write(build.toString());
            writer.close();

            new statusCheck(true, "editted successfully");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editLecturerBtnActionPerformed

    private void editLectBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLectBoxActionPerformed
        String lectID = (String) editLectBox.getSelectedItem();
        try {
            BufferedReader lecturer = new BufferedReader(new FileReader(Assignment.user));
            String line;

            while ((line = lecturer.readLine()) != null) {
                String[] lect = line.split(", ");
                if (lect[0].equals((lectID))) {
                    editLectName.setText(lect[1]);
                    editLectMail.setText(lect[2]);
                    editLectPass.setText(lect[3]);
                    break;
                }
            }
            lecturer.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_editLectBoxActionPerformed

    private void editStudentBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentBoxActionPerformed
        String studID = (String) editStudentBox.getSelectedItem();
        try {
            BufferedReader student = new BufferedReader(new FileReader(Assignment.student));
            String line;

            while ((line = student.readLine()) != null) {
                String[] stud = line.split(", ");
                if (stud[0].equals((studID))) {
                    editStudName.setText(stud[1]);
                    editStudMail.setText(stud[2]);
                    editStudPass.setText(stud[3]);
                    editSIntBox.setSelectedItem(stud[4]);
                    break;
                }
            }
            student.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editStudentBoxActionPerformed

    private void editStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentBtnActionPerformed

        try {
            BufferedReader reader = new BufferedReader(new FileReader(Assignment.student));
            StringBuilder build = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                String[] col = line.split(", ");
                if (col[0].equals(editStudentBox.getSelectedItem())) {
                    col[1] = editStudName.getText();
                    col[2] = editStudMail.getText();
                    col[3] = editStudPass.getText();
                    col[4] = (String) editSIntBox.getSelectedItem();
                }
                build.append(String.join(", ", col)).append("\n");
            }
            reader.close();

            BufferedWriter writer = new BufferedWriter(new FileWriter(Assignment.student));
            writer.write(build.toString());
            writer.close();

            new statusCheck(true, "editted successfully");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_editStudentBtnActionPerformed

    private void adRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adRegisterBtnActionPerformed
        String name = adName.getText();
        String mail = adMail.getText();
        String pass = adPass.getText();
        String role = "l";

        try {
            BufferedReader reader = new BufferedReader(new FileReader(Assignment.user));
            String line;
            ArrayList<Integer> id = new ArrayList<>();

            while ((line = reader.readLine()) != null) {
                String[] admin = line.split(", ");
                if (name.isEmpty() || mail.isEmpty() || pass.isEmpty()) {
                    statusCheck err = new statusCheck(false, "credentials cannot be empty");
                    return;
                }
                else if (name.toLowerCase().equals(admin[1].toLowerCase()) || mail.equals(admin[2])) {
                    statusCheck err = new statusCheck(false, "this name / email exists within the system");
                    return;
                }
                else {
                    id.add(Integer.parseInt(admin[0]));
                }
            }
            int maxID = 0;

            for (int i : id) {
                if (i > maxID) {
                    maxID = i;
                }
            }
            int finalID = maxID + 1;

            String newLine = String.format("%06d, %s, %s, %s, a", finalID, name, mail, pass );

            BufferedWriter writer = new BufferedWriter(new FileWriter(Assignment.user, true));
            writer.write(newLine);
            writer.newLine();
            writer.close();
            statusCheck done = new statusCheck(true, "admin registered.");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_adRegisterBtnActionPerformed

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        String lectID = (String) assignLBox.getSelectedItem();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(Assignment.user));
            StringBuilder builder = new StringBuilder();
            String line;

            while ((line = reader.readLine()) != null) {
                String[] lec = line.split(", ");
                if (lec[0].equals(lectID)) {
                    lec[4] = "p";
                }
                builder.append(String.join(", ", lec)).append("\n");
            }
            reader.close();

            BufferedWriter writer = new BufferedWriter (new FileWriter(Assignment.user));
            writer.write(builder.toString());
            writer.close();

            new statusCheck(true, "role changed successfully");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_assignButtonActionPerformed

    private void studRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studRegisterBtnActionPerformed
        String name = studName.getText();
        String mail = studMail.getText();
        String pass = studPass.getText();
        String intake = (String) studIntakeBox.getSelectedItem();

        try {
            BufferedReader reader = new BufferedReader(new FileReader(Assignment.student));
            String line;
            ArrayList<Integer> id = new ArrayList<>();

            while ((line = reader.readLine()) != null) {
                String[] student = line.split(", ");
                if (name.isEmpty() || mail.isEmpty() || pass.isEmpty()) {
                    statusCheck err = new statusCheck(false, "credentials cannot be empty");
                    return;
                }
                else if (name.toLowerCase().equals(student[1].toLowerCase()) || mail.equals(student[2])) {
                    statusCheck err = new statusCheck(false, "this student exists with the inserted email / name");
                    return;
                }
                else {
                    id.add(Integer.parseInt(student[0]));
                }
            }
            int maxID = 0;

            for (int i : id) {
                if (i > maxID) {
                    maxID = i;
                }
            }
            int finalID = maxID + 1;

            String newLine = String.format("%06d, %s, %s, %s, %s", finalID, name, mail, pass, intake);

            BufferedWriter writer = new BufferedWriter(new FileWriter(Assignment.student, true));
            writer.write(newLine);
            writer.newLine();
            writer.close();
            statusCheck done = new statusCheck(true, "student registered.");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_studRegisterBtnActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            try {
                BufferedReader reader = new BufferedReader(new FileReader(Assignment.intake));
                String line;

                while ((line = reader.readLine()) != null) {
                    String[] intake = line.split(", ");
                    studIntakeBox.addItem(intake[0]);
                }
            }
            catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void lectRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectRegisterBtnActionPerformed
        String name = lectName.getText();
        String mail = lectMail.getText();
        String pass = lectPass.getText();
        String role = "l";

        try {
            BufferedReader reader = new BufferedReader(new FileReader(Assignment.user));
            String line;
            ArrayList<Integer> id = new ArrayList<>();

            while ((line = reader.readLine()) != null) {
                String[] lecturer = line.split(", ");
                if (name.isEmpty() || mail.isEmpty() || pass.isEmpty()) {
                    statusCheck err = new statusCheck(false, "credentials cannot be empty");
                    return;
                }
                else if (name.toLowerCase().equals(lecturer[1].toLowerCase()) || mail.equals(lecturer[2])) {
                    statusCheck err = new statusCheck(false, "this name / email exists within the system");
                    return;
                }
                else {
                    id.add(Integer.parseInt(lecturer[0]));
                }
            }
            int maxID = 0;

            for (int i : id) {
                if (i > maxID) {
                    maxID = i;
                }
            }
            int finalID = maxID + 1;
            if (jCheckBox2.isSelected()) {
                role = "p";
            }
            String newLine = String.format("%06d, %s, %s, %s, %s", finalID, name, mail, pass, role);

            BufferedWriter writer = new BufferedWriter(new FileWriter(Assignment.user, true));
            writer.write(newLine);
            writer.newLine();
            writer.close();
            statusCheck done = new statusCheck(true, "lecturer registered.");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lectRegisterBtnActionPerformed

    private void assignVar() {
        try {

            BufferedReader lecturer = new BufferedReader(new FileReader(Assignment.user));
            String line1;
            
            while ((line1 = lecturer.readLine()) != null) {
                String[] lec = line1.split(", ");
                if (lec[4].equals("l")) {
                    assignLBox.addItem(lec[0]);
                    editLectBox.addItem(lec[0]);
                }
                else if (lec[4].equals("p")) {
                    editProjBox.addItem(lec[0]);
                }
                else if (lec[4].equals("a")) {
                    editAdBox.addItem(lec[0]);
                }
            }
            lecturer.close();
            
            //student
            BufferedReader student = new BufferedReader(new FileReader(Assignment.student));
            String line2;
            
            while ((line2 = student.readLine()) != null) {
                String[] stud = line2.split(", ");
                editStudentBox.addItem(stud[0]);
            }
            student.close();
            
            BufferedReader intake = new BufferedReader(new FileReader(Assignment.intake));
            String line3;

            while ((line3 = intake.readLine()) != null) {
                String[] inta = line3.split(", ");
                editSIntBox.addItem(inta[0]);
            }
            intake.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane adMail;
    private javax.swing.JTextPane adName;
    private javax.swing.JTextPane adPass;
    private javax.swing.JButton adRegisterBtn;
    private javax.swing.JButton assignButton;
    private javax.swing.JComboBox<String> assignLBox;
    private javax.swing.JComboBox<String> editAdBox;
    private javax.swing.JTextPane editAdMail;
    private javax.swing.JTextPane editAdName;
    private javax.swing.JTextPane editAdPass;
    private javax.swing.JButton editAdminBtn;
    private javax.swing.JComboBox<String> editLectBox;
    private javax.swing.JTextPane editLectMail;
    private javax.swing.JTextPane editLectName;
    private javax.swing.JTextPane editLectPass;
    private javax.swing.JButton editLecturerBtn;
    private javax.swing.JComboBox<String> editProjBox;
    private javax.swing.JTextPane editProjMail;
    private javax.swing.JTextPane editProjName;
    private javax.swing.JTextPane editProjPass;
    private javax.swing.JButton editProjectBtn;
    private javax.swing.JComboBox<String> editSIntBox;
    private javax.swing.JTextPane editStudMail;
    private javax.swing.JTextPane editStudName;
    private javax.swing.JTextPane editStudPass;
    private javax.swing.JComboBox<String> editStudentBox;
    private javax.swing.JButton editStudentBtn;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextPane lectMail;
    private javax.swing.JTextPane lectName;
    private javax.swing.JTextPane lectPass;
    private javax.swing.JButton lectRegisterBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JComboBox<String> studIntakeBox;
    private javax.swing.JTextPane studMail;
    private javax.swing.JTextPane studName;
    private javax.swing.JTextPane studPass;
    private javax.swing.JButton studRegisterBtn;
    // End of variables declaration//GEN-END:variables
}
